### ISSUE TITLE
这个错误有人知道是怎么回事吗？

### ISSUE THREAD

**Issue by hgq5** [onface/gulp-book#41]
root@rdcnBuild016:/home/share/web_src# gulp
[15:00:31] Using gulpfile /home/share/web_src/gulpfile.js
[15:00:31] Starting 'js'...
[15:00:31] Finished 'js' after 14 ms
[15:00:31] Starting 'jsCopy'...
[15:00:31] Finished 'jsCopy' after 2.33 ms
[15:00:31] Starting 'html'...
[15:00:31] Finished 'html' after 5.07 ms
[15:00:31] Starting 'css'...
[15:00:31] Finished 'css' after 1.24 ms
[15:00:31] Starting 'image'...
[15:00:31] Finished 'image' after 2.28 ms
[15:00:31] Starting 'copy'...
[15:00:31] Finished 'copy' after 525 μs
[15:00:31] Starting 'icon'...
[15:00:31] Finished 'icon' after 1.05 ms
[15:00:31] Starting 'default'...
[15:00:31] Finished 'default' after 2.02 μs

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: gifsicle: unrecognized option ‘--no-app-extensions’
Usage: gifsicle [OPTION | FILE | FRAME]...
Try 'gifsicle --help' for more information.

    at Promise.all.then.arr (/home/share/web_src/node_modules/_execa@0.7.0@execa/index.js:231:11)
    at process._tickCallback (internal/process/next_tick.js:109:7)
root@rdcnBuild016:/home/share/web_src#

**Comment by hgq5** [comment]
单独压缩文件夹里的png文件就没报错，但是压缩gif文件就会出现错误。
